name: Android Emulator Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Android SDK (Fixed Extraction)
        run: |
          # Create SDK directory
          mkdir -p ~/android-sdk/cmdline-tools
          
          # Download command-line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          
          # Extract and fix directory structure
          unzip cmdline-tools.zip -d ~/android-sdk/cmdline-tools-tmp
          mv ~/android-sdk/cmdline-tools-tmp/cmdline-tools ~/android-sdk/cmdline-tools/latest
          rm -rf cmdline-tools.zip ~/android-sdk/cmdline-tools-tmp
          
          # Set environment variables
          echo "ANDROID_HOME=~/android-sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:~/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_ENV
          
          # Install required components
          yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=~/android-sdk --licenses
          ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=~/android-sdk "platform-tools" "emulator" "platforms;android-33" "system-images;android-33;google_apis;x86_64"

      - name: Verify SDK Installation
        run: |
          ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=~/android-sdk --list
          echo "Android tools installed at:"
          ls -la ~/android-sdk

      - name: Launch Emulator
        run: |
          # Create AVD
          ~/android-sdk/cmdline-tools/latest/bin/avdmanager --sdk_root=~/android-sdk create avd -n Pixel_6_API_33 -k "system-images;android-33;google_apis;x86_64" -d pixel_6 --force
          
          # Start emulator
          ~/android-sdk/emulator/emulator -avd Pixel_6_API_33 -no-audio -no-boot-anim -no-snapshot -accel on &
          
          # Wait for device
          ~/android-sdk/platform-tools/adb wait-for-device
          ~/android-sdk/platform-tools/adb shell settings put global window_animation_scale 0
          sleep 30

      - name: Run Tests
        run: |
          npm install
          npx wdio run wdio.conf.js
        env:
          APPIUM_HOST: localhost
          APPIUM_PORT: 4723
